# Generated by Django 6.0.1 on 2026-01-15 02:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('applies_to', models.CharField(choices=[('ORDER_SUBTOTAL', 'Order subtotal'), ('SHIPPING', 'Shipping')], default='ORDER_SUBTOTAL', max_length=20)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('min_subtotal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('max_uses_per_customer', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_redemptions', to='customers.customer')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_redemption', to='orders.order')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='promotions.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('predicate', models.JSONField(blank=True, default=dict)),
                ('action_type', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed')], max_length=10)),
                ('action_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('stackable', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.merchant')),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'is_active'], name='promotions__merchan_0a8233_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('action_type', 'PERCENT'), ('action_value__gt', Decimal('0.00')), ('action_value__lte', Decimal('100.00'))), models.Q(('action_type', 'FIXED'), ('action_value__gte', Decimal('0.00')), models.Q(('currency', ''), _negated=True)), _connector='OR'), name='chk_promotion_action_type_value'), models.CheckConstraint(condition=models.Q(('start_at__isnull', True), ('end_at__isnull', True), ('end_at__gt', models.F('start_at')), _connector='OR'), name='chk_promotion_date_range')],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['merchant', 'is_active'], name='promotions__merchan_e214b0_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['merchant', 'code'], name='promotions__merchan_3e533a_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('merchant', 'code'), name='uniq_voucher_code_per_merchant'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'PERCENT'), ('value__gt', Decimal('0.00')), ('value__lte', Decimal('100.00'))), models.Q(('discount_type', 'FIXED'), ('value__gte', Decimal('0.00')), models.Q(('currency', ''), _negated=True)), _connector='OR'), name='chk_voucher_discount_type_value'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('min_subtotal_amount__isnull', True), ('min_subtotal_amount__gte', Decimal('0.00')), _connector='OR'), name='chk_voucher_min_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('start_at__isnull', True), ('end_at__isnull', True), ('end_at__gt', models.F('start_at')), _connector='OR'), name='chk_voucher_date_range'),
        ),
        migrations.AddIndex(
            model_name='voucherredemption',
            index=models.Index(fields=['voucher', 'redeemed_at'], name='promotions__voucher_d1c27a_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherredemption',
            index=models.Index(fields=['customer', 'redeemed_at'], name='promotions__custome_8b97ac_idx'),
        ),
    ]
