# Generated by Django 6.0.1 on 2026-01-15 02:21

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CHECKOUT', 'Checkout'), ('CONVERTED', 'Converted'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=12)),
                ('token', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('voucher_code_snapshot', models.CharField(blank=True, max_length=40)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CartAppliedDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(max_length=16)),
                ('source_ref', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('DIRECT', 'Direct'), ('BOOKING', 'Booking'), ('WEIGHT', 'Weight')], max_length=16)),
                ('sku_snapshot', models.CharField(blank=True, max_length=64)),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('variant_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('quantity_each', models.PositiveIntegerField(default=0)),
                ('quantity_grams', models.PositiveBigIntegerField(default=0)),
                ('scheduled_start_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_at', models.DateTimeField(blank=True, null=True)),
                ('unit_amount_preview', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_amount_per_gram_preview', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=12)),
                ('line_subtotal_preview', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
