# Generated by Django 6.0.1 on 2026-01-15 02:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cart', '0001_initial'),
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('promotions', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='converted_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_cart', to='orders.order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.merchant'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='promotions.voucher'),
        ),
        migrations.AddField(
            model_name='cartapplieddiscount',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_discounts', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='cartline',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='cartline',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_lines', to='scheduling.resource'),
        ),
        migrations.AddField(
            model_name='cartline',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productvariant'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['merchant', 'status', 'created_at'], name='cart_cart_merchan_2fd26c_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['merchant', 'user', 'status'], name='cart_cart_merchan_2ebe1d_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['merchant', 'token', 'status'], name='cart_cart_merchan_5ab097_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(('currency', ''), _negated=True), name='chk_cart_currency_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', True), ('customer__isnull', True), ('token', ''), _negated=True), name='chk_cart_has_identity'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('token__gt', '')), fields=('merchant', 'token'), name='uniq_cart_token_per_merchant_when_present'),
        ),
        migrations.AddIndex(
            model_name='cartapplieddiscount',
            index=models.Index(fields=['cart'], name='cart_cartap_cart_id_2e77fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartapplieddiscount',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='chk_cart_applied_discount_amount_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='cartline',
            index=models.Index(fields=['cart'], name='cart_cartli_cart_id_c12c78_idx'),
        ),
        migrations.AddIndex(
            model_name='cartline',
            index=models.Index(fields=['variant'], name='cart_cartli_variant_c51429_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartline',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['DIRECT', 'WEIGHT'])), fields=('cart', 'variant'), name='uniq_cart_variant_for_direct_weight'),
        ),
        migrations.AddConstraint(
            model_name='cartline',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'BOOKING')), fields=('cart', 'variant', 'scheduled_start_at', 'scheduled_end_at', 'resource'), name='uniq_cart_booking_same_timespan'),
        ),
        migrations.AddConstraint(
            model_name='cartline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'DIRECT'), ('quantity_each__gt', 0), ('quantity_grams', 0), ('resource__isnull', True), ('scheduled_end_at__isnull', True), ('scheduled_start_at__isnull', True)), models.Q(('kind', 'WEIGHT'), ('quantity_each', 0), ('quantity_grams__gt', 0), ('resource__isnull', True), ('scheduled_end_at__isnull', True), ('scheduled_start_at__isnull', True)), models.Q(('kind', 'BOOKING'), ('quantity_each__gt', 0), ('quantity_grams', 0), ('resource__isnull', False), ('scheduled_end_at__gt', models.F('scheduled_start_at')), ('scheduled_end_at__isnull', False), ('scheduled_start_at__isnull', False)), _connector='OR'), name='chk_cartline_kind_quantities_and_times'),
        ),
    ]
