# Generated by Django 6.0.1 on 2026-01-15 02:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('DIRECT', 'Direct'), ('BOOKING', 'Booking'), ('WEIGHT', 'Weight')], max_length=16)),
                ('unit_price_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('track_inventory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.merchant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('slot_step_minutes', models.PositiveIntegerField(default=30)),
                ('capacity_per_slot', models.PositiveIntegerField(default=1)),
                ('buffer_before_minutes', models.PositiveIntegerField(default=0)),
                ('buffer_after_minutes', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_settings', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='WeightSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_grams', models.PositiveIntegerField(default=50)),
                ('min_grams', models.PositiveIntegerField(default=50)),
                ('max_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_gram_amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weight_settings', to='catalog.productvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['merchant', 'is_active'], name='catalog_pro_merchan_3a5be8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['merchant', 'slug'], name='catalog_pro_merchan_e59798_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('merchant', 'slug'), name='uniq_product_slug_per_merchant'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['merchant', 'sku'], name='catalog_pro_merchan_f075b9_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['merchant', 'kind'], name='catalog_pro_merchan_1e47b4_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['merchant', 'is_active'], name='catalog_pro_merchan_ac6c8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('merchant', 'sku'), name='uniq_sku_per_merchant'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_amount__gte', Decimal('0.00'))), name='chk_variant_unit_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('currency', ''), _negated=True), name='chk_variant_currency_not_empty'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['product', 'sort_order'], name='catalog_pro_product_7a4b52_idx'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['variant', 'sort_order'], name='catalog_pro_variant_abd3b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingsettings',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='chk_booking_settings_duration_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='bookingsettings',
            constraint=models.CheckConstraint(condition=models.Q(('slot_step_minutes__gt', 0)), name='chk_booking_settings_slot_step_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='bookingsettings',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_per_slot__gt', 0)), name='chk_booking_settings_capacity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='weightsettings',
            constraint=models.CheckConstraint(condition=models.Q(('step_grams__gt', 0)), name='chk_weight_settings_step_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='weightsettings',
            constraint=models.CheckConstraint(condition=models.Q(('min_grams__gt', 0)), name='chk_weight_settings_min_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='weightsettings',
            constraint=models.CheckConstraint(condition=models.Q(('max_grams__isnull', True), ('max_grams__gte', models.F('min_grams')), _connector='OR'), name='chk_weight_settings_max_gte_min'),
        ),
        migrations.AddConstraint(
            model_name='weightsettings',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_gram_amount__gte', Decimal('0'))), name='chk_weight_price_nonnegative'),
        ),
    ]
