# Generated by Django 6.0.1 on 2026-01-15 02:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_merchants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], default='STAFF', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['slug'], name='accounts_me_slug_0d9a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['is_active'], name='accounts_me_is_acti_df5440_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantmember',
            index=models.Index(fields=['merchant', 'is_active'], name='accounts_me_merchan_df355b_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantmember',
            index=models.Index(fields=['user', 'is_active'], name='accounts_me_user_id_71b457_idx'),
        ),
        migrations.AddConstraint(
            model_name='merchantmember',
            constraint=models.UniqueConstraint(fields=('merchant', 'user'), name='uniq_member_per_merchant'),
        ),
    ]
