# Generated by Django 6.0.1 on 2026-01-15 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='scheduling.resource'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.productvariant'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['merchant', 'status', 'created_at'], name='orders_orde_merchan_b239a1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['merchant', 'customer', 'created_at'], name='orders_orde_merchan_320f39_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('currency', ''), _negated=True), name='chk_order_currency_not_empty'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['order'], name='orders_orde_order_i_44a8a5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['variant'], name='orders_orde_variant_7f038a_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'DIRECT'), ('quantity_each__gt', 0), ('quantity_grams', 0), ('resource__isnull', True), ('scheduled_end_at__isnull', True), ('scheduled_start_at__isnull', True)), models.Q(('kind', 'WEIGHT'), ('quantity_each', 0), ('quantity_grams__gt', 0), ('resource__isnull', True), ('scheduled_end_at__isnull', True), ('scheduled_start_at__isnull', True)), models.Q(('kind', 'BOOKING'), ('quantity_each__gt', 0), ('quantity_grams', 0), ('resource__isnull', False), ('scheduled_end_at__gt', models.F('scheduled_start_at')), ('scheduled_end_at__isnull', False), ('scheduled_start_at__isnull', False)), _connector='OR'), name='chk_orderline_kind_quantities_and_times'),
        ),
    ]
