# Generated by Django 6.0.1 on 2026-01-15 02:21

import django.contrib.postgres.constraints
import django.contrib.postgres.operations
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timespan', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('status', models.CharField(choices=[('HOLD', 'Hold'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='HOLD', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='customers.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.merchant')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='orders.order')),
                ('order_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='orders.orderline')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.productvariant')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='scheduling.resource')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.merchant')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='scheduling.resource')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('BLOCK', 'Block'), ('ADD', 'Add')], default='BLOCK', max_length=8)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.merchant')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_overrides', to='scheduling.resource')),
            ],
        ),
        migrations.CreateModel(
            name='VariantResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_links', to='scheduling.resource')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='catalog.productvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['merchant', 'is_active'], name='scheduling__merchan_f0ff70_idx'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('merchant', 'name'), name='uniq_resource_name_per_merchant'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['merchant', 'resource', 'status'], name='scheduling__merchan_777881_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['merchant', 'variant', 'status'], name='scheduling__merchan_82067d_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['HOLD', 'CONFIRMED'])), expressions=[('resource', '='), ('timespan', '&&')], name='exclude_overlapping_bookings_per_resource'),
        ),
        migrations.AddIndex(
            model_name='availabilityrule',
            index=models.Index(fields=['merchant', 'resource', 'weekday'], name='scheduling__merchan_aeac71_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityrule',
            index=models.Index(fields=['merchant', 'is_active'], name='scheduling__merchan_1ed6af_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='chk_availability_rule_time_range'),
        ),
        migrations.AddIndex(
            model_name='availabilityoverride',
            index=models.Index(fields=['merchant', 'resource', 'start_at'], name='scheduling__merchan_e8a27a_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityoverride',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='chk_availability_override_range'),
        ),
        migrations.AddIndex(
            model_name='variantresource',
            index=models.Index(fields=['resource', 'variant'], name='scheduling__resourc_a40c18_idx'),
        ),
        migrations.AddConstraint(
            model_name='variantresource',
            constraint=models.UniqueConstraint(fields=('variant', 'resource'), name='uniq_variant_resource'),
        ),
    ]
